@baseUrl = http://localhost:3000

### Recuperando todos os recados

GET {{baseUrl}}/recados/

### Recuperando recado por id

GET {{baseUrl}}/recados/13

### Criando recado 

POST {{baseUrl}}/recados
Content-Type: application/json

{
    "name": "Esse é um recado"
}

### Atualiza o recado
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
    "name": "Esse é um recado"
}

### Apaga recado por id

GET {{baseUrl}}/recados/13