services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: memos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
