@baseUrl = http://localhost:3000

### Recuperando todos os recados

GET {{baseUrl}}/memos/
?limit=2
&offset=1

### Recuperando recado por id

GET {{baseUrl}}/memos/7

### Criando recado 

POST {{baseUrl}}/memos
Content-Type: application/json

  {
    "text": "Novo Recado",
    "fromId": 2,
    "toId": 4
  }

### Atualiza o recado
PATCH {{baseUrl}}/memos/7
Content-Type: application/json

  {
    "text": "Atualizando textooo",
    "wasRead": true
  }

### Apaga recado por id

DELETE  {{baseUrl}}/memos/4