@baseUrl = http://localhost:3000

### Recebe 'Qualquer coisa'

GET {{baseUrl}}/home/hello

### Recebe 'exemplo'

GET {{baseUrl}}/home/exemplo

### Conceitos manueal controller

GET {{baseUrl}}/conceitos-manual

### Conceitos automatico controller

GET {{baseUrl}}/conceitos-automatico

### Conceitos Manuais get hello service

GET {{baseUrl}}/conceitos-manual/service

### Conceitos Manuais get hello service

GET {{baseUrl}}/conceitos-automatico/service